Server:
  InternalPort: 5000
  ExternalPort: 9001
  RunMode: debug
Logger: 
  Filepath: /logs/
  Encoding: json
  Level: debug
  Logger: zerolog
Cors: 
  AllowOrigins: "*"
Postgres: 
  Host: postgres_container
  Port: 5432
  User: postgres
  PassWord: admin
  dbName: car_sale_db
  sslMode: disable
  MaxIdleConns: 15
  SetMaxOpenConns: 100
  SetConnMaxLifetime: 5
redis: 
  Host: redis_container
  Port: 6379
  PassWord: password
  db: 0
  dialTimeout: 5
  readTimeout: 5
  writeTimeout: 5
  idleCheckFrequency: 500
  pollsize: 10
  poolTimeout: 15
otp:
  expireTime: 120
  digits: 6
  limiter: 100
password:
  includeChars: true
  includeDigits: true
  minLength: 6
  maxLength: 64
  includeUppercase: true
  includeLowercase: true
jwt: 
  secret: "secret"
  refreshSecret: "refreshSecret"
  accessTokenExpireDuration: 10000
  refreshTokenExpireDuration: 60
